landr/config/routes.rb
Landr::Application.routes.draw do
  root "sites#index"
  get "l/:short_name" => "sites#landing",
    as: 'site_landing'
  post "l/:short_name" => "sites#signup"

  resources :sites

  devise_for :users

end

landr/app/models/prospect.rb
class Prospect < ActiveRecord::Base
	belongs_to :site

end

landr/app/models/site.rb
class Site < ActiveRecord::Base
	belongs_to :user
	has_many :prospects, dependent: :destroy
	
end

landr/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :sites, dependent: :destroy
end

landr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

landr/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /sites
  # GET /sites.json
  def index
    @sites = current_user.sites
    logger.debug "CURRENT_USER: #{current_user}"
    #logger.debug ""
  end
def landing
  short_name = params[:short_name]
  logger.debug "USER PASSED: #{short_name}"
  @site = Site.where(short_name: short_name).first
  @prospect = Prospect.new
  logger.debug "FOUND SITE: #{@site}"
  render layout: 'landing'
end

def signup
  prospect = Prospect.new(prospect_params)
  short_name = params[:short_name]
  site = Site.where(short_name: short_name).first
  prospect.site = site
  prospect.save
  flash[:notice] = "Thanks, We will email you when the site is ready!!"
  redirect_to action: :landing
end
  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)
    @site.user = current_user

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    if @site.user != current_user
      raise "This is an issue"
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:site_url, :background_url, :message, :short_name)
    end

    def prospect_params
      params.require(:prospect).permit(:email)
    end
end

landr/app/helpers/application_helper.rb
module ApplicationHelper
end

landr/app/helpers/sites_helper.rb
module SitesHelper
end

landr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Landr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Landr</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

landr/app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Landr" %></title>
    <%= csrf_meta_tags %>
</head>
<body>

 <p class="notice".,%= notice %></p>
 <p class="alert".,%= alert %></p>
<%= yield %>

</body>
</html>

landr/app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :background_url %><br>
    <%= f.text_field :background_url %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

landr/app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

landr/app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <thead>
    <tr>
      <th>Site url</th>
      <th>Background url</th>
      <th>Message</th>
      <th>Short name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.site_url %></td>
        <td><%= site.background_url %></td>
        <td><%= site.message %></td>
        <td><%= site.short_name %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

landr/app/views/sites/landing.html.erb
Site URL: <%= @site.site_url %>
<br/>
Site Short Name: <%= @site.short_name %>

<%= form_for(@prospect, url: { action: 'signup'}) do |f| %>
	<%= f.text_field :email %>
	<%= f.submit %>

<% end %>
<style>
body 
{ background-image: url('<%= @site.background_url %>');
	background-size: 50%;
}
</style>

landr/app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

landr/app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site url:</strong>
  <%= @site.site_url %>
</p>

<p>
  <strong>Background url:</strong>
  <%= @site.background_url %>
</p>

<p>
  <strong>Message:</strong>
  <%= @site.message %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @site.short_name %>
</p>

<p>
  <strong> Landing Page URL: </strong>
  <%= link_to(site_landing_url(@site.short_name)) %>
</p>

<p>
	<strong> Prospects </strong>
	<ul>
	<% @site.prospects.each do |prospect| %>
	<li> <%= prospect.email %></li>
		<% end %>
	</ul>
</p>
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>